# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Stronger
email: mikedecosta@codestronger.com
description: > # this means to ignore newlines until "baseurl:"
    Start getting more out of your code with less effort. Start coding stronger.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codestronger.com" # the base hostname & protocol for your site
github_username:  mikedecosta
twitter_username: code_stronger

# Build settings
markdown: kramdown

# Publish settings
future: false
show_drafts: false

# Theme settings
theme: jekyll-theme-hacker

# Prose editor settings
prose:
  rooturl: '_posts'
  siteurl: 'http://codestronger.com/'
  relativeLinks: 'http://codestronger.com/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""