# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Stronger
email: mikedecosta@codestronger.com
description: > # this means to ignore newlines until "baseurl:"
    Start getting more out of your code with less effort. Start coding stronger.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codestronger.com" # the base hostname & protocol for your site
github_username:  mikedecosta
twitter_username: code_stronger

# Build settings
markdown: kramdown

# Publish settings
future: false
show_drafts: false

theme: jekyll-theme-hacker
