# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Super Programmer
email: mikedecosta@superprogrammer.com
description: > # this means to ignore newlines until "baseurl:"
    Become that mythical super programmer every organization wishes they had.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://superprogrammer.com" # the base hostname & protocol for your site
twitter_username: mikedecosta1
github_username:  mikedecosta

# Build settings
markdown: kramdown
